version: '3'
services:
  vault:
   image: vault:1.13.3
   container_name: prodvault
   environment:
      VAULT_ADDR: http://127.0.0.1:8200
   ports:
      - "8200:8200"
   volumes:
      - private-volume:/vault/file:rw
      - ./vault:/vault/config:rw
   cap_add:
      - IPC_LOCK
   entrypoint: vault server -config=/vault/config/vault.json

volumes:
  private-volume: