version: '3'
services:
  spring-app:
    image: maven:3-openjdk-17-slim
    container_name: spring-app-container
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    command: mvn -f /app/pom.xml spring-boot:run
    working_dir: /app
