name: Testing Pipeline

on:
  pull_request:
    branches: ['dev']
    types: [opened, synchronize]
  push:
    branches: ['partialDevelopmentOfControllerLogic']

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Run Maven Tests
      run: |
        cd backend/
        mvn test -Dtest=ReservationControllerTest,ReviewControllerTest,ServiceControllerTest,UserControllerTest