name: Testing

on:
  pull_request:
    branches: ['dev']
    types: [opened, synchronize]
  push:
    branches: ['partialDevelopmentOfControllerLogic']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: echo message
      run: echo "hello world"